In [1]:
import cv2 as cv
import os

In [2]:
image=cv.imread('c:/Users/dell/Desktop/SALLY/DATA/image1.png')
 
image = cv.imread("../data/image1.png")

print(image)
 

[[[118 138 229]
  [129 137 228]
  [129 137 228]
  ...
  [117 151 234]
  [119 128 220]
  [ 95  99 194]]

 [[129 137 228]
  [129 130 218]
  [129 137 228]
  ...
  [127 144 230]
  [104 129 222]
  [ 93  97 205]]

 [[124 141 220]
  [129 137 228]
  [129 137 228]
  ...
  [118 144 234]
  [111 131 223]
  [ 87  90 199]]

 ...

 [[ 60  16  80]
  [ 59  18  86]
  [ 66  24  89]
  ...
  [ 82  74 181]
  [ 83  70 176]
  [ 80  64 172]]

 [[ 59  18  86]
  [ 59  18  86]
  [ 61  24  96]
  ...
  [ 82  74 181]
  [ 82  74 181]
  [ 82  74 181]]

 [[ 60  16  80]
  [ 59  18  86]
  [ 71  30  96]
  ...
  [ 80  66 176]
  [ 76  69 183]
  [ 82  75 189]]]


In [3]:
grey=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
print(grey)

[[163 163 163 ... 172 154 127]
 [163 156 163 ... 168 154 129]
 [163 163 163 ... 168 156 122]
 ...
 [ 40  43  48 ... 107 103  98]
 [ 43  43  50 ... 107 107 107]
 [ 40  43  54 ... 100 104 110]]


In [4]:
#to check the nb of channels
print(image.shape)  #prints a tuple (height,width,channels)
print(grey.shape)   #prints a tuple (height,width)

(512, 512, 3)
(512, 512)


In [5]:
rgb_image=cv.imread('../data/rgb_image.jpg')
print(rgb_image.shape)  #prints a tuple (height,width,channels)

(360, 639, 3)


In [3]:
rgb_image=cv.cvtColor(rgb_image,cv.COLOR_BGR2RGB)
print(rgb_image.shape)

NameError: name 'rgb_image' is not defined

In [9]:
image1=cv.imread('../data/colors.jpg')
rgb_image=cv.cvtColor(image1,cv.COLOR_BGR2RGB)

In [5]:
(r,g,b)=cv.split(rgb_image)

In [8]:
cv.namedWindow("Red",cv.WINDOW_NORMAL)
cv.imshow("Red",r)
cv.namedWindow("Green",cv.WINDOW_NORMAL)
cv.imshow("Green",g)
cv.namedWindow("Blue",cv.WINDOW_NORMAL)
cv.imshow("Blue",b)
            

In [ ]:
cv.imwrite('red_channel.jpg',r)
cv.imwrite('green_channel.jpg',g) 
cv.imwrite('blue_channel.jpg',b)

if cv.waitKey(0):
    cv.destroyAllWindows() 

 
 

In [ ]:
#find the pixel value at (0,0) which is first pixel of the image
(b,g,r)=rgb_image[0,0]
print("At pixel (0,0) - Red: {}, Green: {}, Blue: {}".format(r,g,b))


At pixel (0,0) - Red: 12, Green: 141, Blue: 42


Drawing


In [1]:
import cv2 as cv
import numpy as np

In [9]:

canvas=np.zeros((300,300,3),dtype="uint8")
green=(0,255,0)
#draw a green line 
cv.line(canvas,(0,0),(300,300),green,5)
cv.imshow("Canvas",canvas)
cv.waitKey(0)


-1

In [11]:
red=(0,0,255) #it is in BGR format since we didnt convert yet
#draw a red line 
cv.line(canvas,(0,300),(300,0),red,5)
cv.imshow("Canvas",canvas)
cv.waitKey(0)

-1

In [27]:
#draw a rectagle
canvas=np.zeros((300,300,3),dtype="uint8")
cv.rectangle(canvas,(10,30),(100,200),green,5)
cv.imshow("Canvas",canvas)  
cv.waitKey(0)

-1

In [28]:
cv.rectangle(canvas,(10,30),(100,200),red,-1)
cv.imshow("Canvas",canvas)  
cv.waitKey(0)

-1

In [30]:

canvas=np.zeros((300,300,3),dtype="uint8")
canvas[:] = (255,0,0) #blue background
cv.imshow("Canvas",canvas)  
cv.waitKey(0)

-1

In [39]:

canvas=np.zeros((300,300,3),dtype="uint8")
canvas.shape
white=(255,255,255)

In [40]:
centerx,centery=canvas.shape[1]//2,canvas.shape[0]//2 #width//2,height//2
print(centerx,centery)


150 150


In [42]:
for r in range(0,150,25): #(start,stop,step) 150/25=6 circles
    cv.circle(canvas,(centerx,centery),r,white)
cv.imshow("Canvas",canvas)  
cv.waitKey(0)

-1

In [41]:
cv.circle(canvas,(centerx,centery),50,(0,255,0),-1)
cv.imshow("Canvas",canvas)  
cv.waitKey(0)

-1

In [45]:
for i in range(0,25):
    radius=np.random.randint(5,200)
    color=np.random.randint(0,256,size=(3,)).tolist()   
    pt=np.random.randint(0,300,size=(2,)) #x and y coordinates
    cv.circle(canvas,pt,radius,color,-1)
cv.imshow("Canvas",canvas)  
cv.waitKey(0)

-1